eureka-server:
  image: server:0.0.1-SNAPSHOT
  ports:
   - "1111:1111"
  hostname: eureka-server
client:
  image: client:0.0.1-SNAPSHOT
  links:
   - eureka-server
  hostname: eureka-client
  ports:
   - "8080:8080"
  environment:
   EUREKA_HOST: eureka-server
   EUREKA_PORT: 1111